services:
  postgres:
    image: postgres:latest
    container_name: healthcare-postgres
    restart: always
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - "$DB_PORT:5432"
